### ISSUE TITLE
Clean up KerasImageFileEstimator params

### ISSUE THREAD

**Issue by smurching** [databricks/spark-deep-learning#113]
Before releasing DLP 1.0, we should take the opportunity to clean-up KerasImageFileEstimator's params. Specifically we should:

* Update `KerasImageFileEstimator.validateParams` to check that the `imageLoader` and `modelFile` params aren't being tuned. Right now if a user passes said params in a paramMap passed to `fit` or `fitMultiple`, we silently ignore the passed params & just use the param values already set in the estimator.
* Check to make sure we don't have any other untunable params like those mentioned above.
* Remove unused params e.g. `inputImageNodeName`, `outputImageNodeName`

**Comment by yogeshg** [comment]
https://github.com/databricks/spark-deep-learning/pull/116 and https://github.com/databricks/spark-deep-learning/pull/117 fixes this

**Comment by smurching** [comment]
Thanks @yogeshg for the PRs! Closing this issue :)
