### ISSUE TITLE
DeepImageFeaturizer - Number of dimensions in output

### ISSUE THREAD

**Issue by lukewgreen** [databricks/spark-deep-learning#134]
Hello,

I'm using DeepImageFeaturizer to transform a set of images into feature vectors, but those feature vectors are unexpectedly large.

For example, when I transform this image: http://www.avatarsdb.com/avatars/spongebob_happy.jpg

The length of the 'features' vector is 131,072. The jpeg itself is 100x100. 

Here is the code I'm using to transform:

`from sparkdl import readImages
from sparkdl import DeepImageFeaturizer

images_path = '[PATH_TO_IMAGE_FOLDER]'
jobs_df = readImages(images_path)

featurizer = DeepImageFeaturizer(inputCol="image", outputCol="features", modelName="InceptionV3")

jobs_df2 = featurizer.transform(jobs_df).cache()
print(len(jobs_df2.select('features').take(1)[0][0])
`

Is there something I'm doing wrong and if not, is there a way to reduce the number of dimensions of the output?

**Comment by lucashu1** [comment]
Not sure if you're still having issues with this or not, but try using a model other than InceptionV3. ResNet50, for example, returns a feature vector of size 2048, which seems a lot more sane for most datasets.

Regarding dimensionality reduction, Spark's `PCA` implementation seems to have an input-dimensionality limit of [65,535](https://community.hortonworks.com/questions/48498/javalangillegalargumentexception-argument-with-mor.html), which means that you can't perform PCA on the features extracted by `DeepImageFeaturizer` if you're using InceptionV3. PCA should work on most of the other featurization models though, provided that they return smaller feature vectors.

**Comment by lukewgreen** [comment]
Hello,

Thanks for replying! I will give ResNet50 a try. I also developed a questionable workaround as it appears that the layer returned by InceptionV3 is the layer before the final average pooling although it does appear to use a different size filter than the one implemented in Keras (I'm assuming it uses an 8x8 filter since 131,072 / 64 = 2048):

```
from pyspark.ml.linalg import VectorUDT, Vector,DenseVector
import pyspark.sql.functions as F

def avg_pool(x,size = 131072,step = 64):
     return DenseVector([sum(x[i:i+step])/step for i in list(np.arange(0,size,step))])

avg_poolUDF = pyspark.sql.functions.udf(avg_pool,VectorUDT())
```

It returns reasonable/useful results although I'm not sure if they're ideal. I'm going to try max pooling next.
