### ISSUE TITLE
error while running python unit test

### ISSUE THREAD

**Issue by a7b23** [databricks/spark-deep-learning#27]
I get an error saying 
'ImportError: No module named tensorframes'

Can you suggest as to how do I install it?

**Comment by sueann** [comment]
Did you run `build/sbt assembly` before running `run-tests.sh` ? The assembly should pull in tensorframes automatically, and `run-tests.sh` should add the built assembly to PYTHONPATH, so you shouldn't need to do anything specific for tensoframes.

**Comment by a7b23** [comment]
Yeah its working fine now .. thanks a lot

**Comment by sueann** [comment]
cool! please re-open if you run into any other issues.

**Comment by xiaoerhei** [comment]
Does it only supports python2 now? it seems if I use the python3, it still shows “No module named 'tensorframes'“ error.
