### ISSUE TITLE
All Tranformer inputs seems to be focused on image files

### ISSUE THREAD

**Issue by charlesa101** [databricks/spark-deep-learning#33]
How do I handle a non-image inputs, i.e numerical time series input ?

**Comment by mavencode01** [comment]
same issue here, we need to handle non-image inputs

**Comment by sueann** [comment]
@charlesa101 @mavencode01 would you be okay with a 1-d tensor, or do you need multi-dimensional tensor inputs? 1-d should be pretty easy to add.

**Comment by charlesa101** [comment]
@sueann thanks, we can start with 1-d tensor for now and adapt it later on to multi-d tensor, in my case, i want to use this on time-series datasets and a 1-d tensor should be just fine

**Comment by smurching** [comment]
#78  and #82 add the `TFTransformer` and `KerasTransformer` APIs for applying Keras/TensorFlow models to 1D & 2D tensor inputs, closing this issue for now.

**Comment by charlesa101** [comment]
Awesome! This is neat 👍
