### ISSUE TITLE
Problem using Sparkdl and readImages

### ISSUE THREAD

**Issue by fsahba** [databricks/spark-deep-learning#37]
Hello all

I have a big problem using databricks notebook and python for reading image. In fact I am trying to run the following code:

from sparkdl import readImages

but it generates error "No module named sparkdl"

When I try to install sparkdl using create library in Databricks, it cannot find sparkdl. Even by adding library
"spark deep learning", it still can not recognize sparkdl.
Does this have other name for installation in Databricks notebook or is there any other way to install sparkdl within my notebook?

Your help is really appreciated

Thanks a lot

Fari

**Comment by sueann** [comment]
Are you creating a library from the spark package? It requires choosing this option in the library creation menu: https://docs.databricks.com/user-guide/libraries.html#libraries-from-maven-pypi-or-spark-packages and searching for "spark-deep-learning" (can take a few minutes to load and you may need to try searching a couple of times).

**Comment by fsahba** [comment]
Thanks a lot.
It was resolved.
Farhang

**Comment by sueann** [comment]
cool, glad to be of help!
