### ISSUE TITLE
How to get the vector used in image search

### ISSUE THREAD

**Issue by swgr** [databricks/spark-deep-learning#73]
Hello,
In the Summit you gave a demo to search similar shoes with 
lsh = BucketedRandomProjectionLSH(inputCol="features", outputCol="..", bucketLength=..,
                                      numHashTables=..)
model = lsh.fit(features_)
model.approxNearestNeighbors(features_,key, n)

Do you have a concrete example to show how to get "key" Vector from an input image?

Thanks
Wanchun

**Comment by sueann** [comment]
If you have the `filePath` for the "key" shoes you want, something like 
```
features_.filter(col('filePath') == 'YOUR_FILEPATH_HERE').first()['features']
```
should work.

**Comment by swgr** [comment]
it works, thanks for the tip!

**Comment by thunterdb** [comment]
Closing this ticket.
