### ISSUE TITLE
is there a mail list for this project?

### ISSUE THREAD

**Issue by AEDWIP** [databricks/spark-deep-learning#80]
I currently working on a deep learning project using time series data. I am interested in learning more and possibly contributing to this project. What is the best way to ask questions

for example does spark-deep-learning scale out linearly?

Happy Thanksgiving

Andy

**Comment by sueann** [comment]
Here is the brand-new mailing list: https://groups.google.com/forum/#!forum/dl-pipelines-users. Thanks for asking :-)

For the linear scale-out, inference should scale out mostly linearly, but there can be some overhead, and as usual with Spark good partition number matters. Is there a particular type of workload you're thinking about? (We can move the conversation to the mailing list if you want)
